name: WEBSOCKET WORKFLOW

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Code
              uses: actions/checkout@v3

            - name: Login to Docker
              uses: docker/login-action@v4
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}
            
            - name: Build and push ##This will first build the Image and them Deploy it to the Docker Hub
              uses: docker/build-push-action@v7
              with:
                context: . ## Context means from where do you want to build, We will build it from the root folder
                file: ./docker/Dockerfile.ws
                push: true
                tags: cryptingle/todo-websocket:${{ github.sha }}
            
            - name: Deploy to VM ##
              run: |
                mkdir -p ~/.ssh    
                echo "${{ secrets.EC2_SSH_PVT_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
                ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST}} "docker pull cryptingle/todo-websocket:${{ github.sha }} || true && docker stop todo-websocket || true && docker rm -f todo-websocket || true && docker run --name todo-websocket --restart unless-stopped -d -p 8081:8081 cryptingle/todo-websocket:${{ github.sha }}"

# ssh-keyscan -H ${{ secrets.EC2_HOST_DEV }} >> ~/.ssh/known_hosts instead of this we can also do ssh -o StrictHostKeyChecking=no -i <pvt key address>
#In the above we didn't use -i because by default it will take id_rsa key